name: Lint

on:
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
